// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AckCommand.proto

package com.arckal.soul.protos;

public final class AckCommandOuterClass {
  private AckCommandOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AckCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.arckal.soul.AckCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool remain = 1;</code>
     */
    boolean getRemain();

    /**
     * <code>string readLastMsgId = 2;</code>
     */
    java.lang.String getReadLastMsgId();
    /**
     * <code>string readLastMsgId = 2;</code>
     */
    com.google.protobuf.ByteString
        getReadLastMsgIdBytes();

    /**
     * <code>string timestamp = 3;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <code>string timestamp = 3;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <code>.com.arckal.soul.AckCommand.Type type = 4;</code>
     */
    int getTypeValue();
    /**
     * <code>.com.arckal.soul.AckCommand.Type type = 4;</code>
     */
    com.arckal.soul.protos.AckCommandOuterClass.AckCommand.Type getType();
  }
  /**
   * Protobuf type {@code com.arckal.soul.AckCommand}
   */
  public  static final class AckCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.arckal.soul.AckCommand)
      AckCommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AckCommand.newBuilder() to construct.
    private AckCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AckCommand() {
      readLastMsgId_ = "";
      timestamp_ = "";
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AckCommand();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AckCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              remain_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              readLastMsgId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              timestamp_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.arckal.soul.protos.AckCommandOuterClass.internal_static_com_arckal_soul_AckCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.arckal.soul.protos.AckCommandOuterClass.internal_static_com_arckal_soul_AckCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.arckal.soul.protos.AckCommandOuterClass.AckCommand.class, com.arckal.soul.protos.AckCommandOuterClass.AckCommand.Builder.class);
    }

    /**
     * Protobuf enum {@code com.arckal.soul.AckCommand.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MSG = 0;</code>
       */
      MSG(0),
      /**
       * <code>SYNC = 1;</code>
       */
      SYNC(1),
      /**
       * <code>UNRECOGNIZED = -1;</code>
       */
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MSG = 0;</code>
       */
      public static final int MSG_VALUE = 0;
      /**
       * <code>SYNC = 1;</code>
       */
      public static final int SYNC_VALUE = 1;
      /**
       * <code>UNRECOGNIZED = -1;</code>
       */
      public static final int UNRECOGNIZED_VALUE = -1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return MSG;
          case 1: return SYNC;
          case -1: return UNRECOGNIZED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.arckal.soul.protos.AckCommandOuterClass.AckCommand.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.arckal.soul.AckCommand.Type)
    }

    public static final int REMAIN_FIELD_NUMBER = 1;
    private boolean remain_;
    /**
     * <code>bool remain = 1;</code>
     */
    public boolean getRemain() {
      return remain_;
    }

    public static final int READLASTMSGID_FIELD_NUMBER = 2;
    private volatile java.lang.Object readLastMsgId_;
    /**
     * <code>string readLastMsgId = 2;</code>
     */
    public java.lang.String getReadLastMsgId() {
      java.lang.Object ref = readLastMsgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        readLastMsgId_ = s;
        return s;
      }
    }
    /**
     * <code>string readLastMsgId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getReadLastMsgIdBytes() {
      java.lang.Object ref = readLastMsgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        readLastMsgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private volatile java.lang.Object timestamp_;
    /**
     * <code>string timestamp = 3;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <code>string timestamp = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>.com.arckal.soul.AckCommand.Type type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.arckal.soul.AckCommand.Type type = 4;</code>
     */
    public com.arckal.soul.protos.AckCommandOuterClass.AckCommand.Type getType() {
      @SuppressWarnings("deprecation")
      com.arckal.soul.protos.AckCommandOuterClass.AckCommand.Type result = com.arckal.soul.protos.AckCommandOuterClass.AckCommand.Type.valueOf(type_);
      return result == null ? com.arckal.soul.protos.AckCommandOuterClass.AckCommand.Type.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (remain_ != false) {
        output.writeBool(1, remain_);
      }
      if (!getReadLastMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, readLastMsgId_);
      }
      if (!getTimestampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, timestamp_);
      }
      if (type_ != com.arckal.soul.protos.AckCommandOuterClass.AckCommand.Type.MSG.getNumber()) {
        output.writeEnum(4, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (remain_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, remain_);
      }
      if (!getReadLastMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, readLastMsgId_);
      }
      if (!getTimestampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, timestamp_);
      }
      if (type_ != com.arckal.soul.protos.AckCommandOuterClass.AckCommand.Type.MSG.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.arckal.soul.protos.AckCommandOuterClass.AckCommand)) {
        return super.equals(obj);
      }
      com.arckal.soul.protos.AckCommandOuterClass.AckCommand other = (com.arckal.soul.protos.AckCommandOuterClass.AckCommand) obj;

      if (getRemain()
          != other.getRemain()) return false;
      if (!getReadLastMsgId()
          .equals(other.getReadLastMsgId())) return false;
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
      if (type_ != other.type_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REMAIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRemain());
      hash = (37 * hash) + READLASTMSGID_FIELD_NUMBER;
      hash = (53 * hash) + getReadLastMsgId().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.arckal.soul.protos.AckCommandOuterClass.AckCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.arckal.soul.protos.AckCommandOuterClass.AckCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.arckal.soul.protos.AckCommandOuterClass.AckCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.arckal.soul.protos.AckCommandOuterClass.AckCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.arckal.soul.protos.AckCommandOuterClass.AckCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.arckal.soul.protos.AckCommandOuterClass.AckCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.arckal.soul.protos.AckCommandOuterClass.AckCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.arckal.soul.protos.AckCommandOuterClass.AckCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.arckal.soul.protos.AckCommandOuterClass.AckCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.arckal.soul.protos.AckCommandOuterClass.AckCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.arckal.soul.protos.AckCommandOuterClass.AckCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.arckal.soul.protos.AckCommandOuterClass.AckCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.arckal.soul.protos.AckCommandOuterClass.AckCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.arckal.soul.AckCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.arckal.soul.AckCommand)
        com.arckal.soul.protos.AckCommandOuterClass.AckCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.arckal.soul.protos.AckCommandOuterClass.internal_static_com_arckal_soul_AckCommand_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.arckal.soul.protos.AckCommandOuterClass.internal_static_com_arckal_soul_AckCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.arckal.soul.protos.AckCommandOuterClass.AckCommand.class, com.arckal.soul.protos.AckCommandOuterClass.AckCommand.Builder.class);
      }

      // Construct using com.arckal.soul.protos.AckCommandOuterClass.AckCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        remain_ = false;

        readLastMsgId_ = "";

        timestamp_ = "";

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.arckal.soul.protos.AckCommandOuterClass.internal_static_com_arckal_soul_AckCommand_descriptor;
      }

      @java.lang.Override
      public com.arckal.soul.protos.AckCommandOuterClass.AckCommand getDefaultInstanceForType() {
        return com.arckal.soul.protos.AckCommandOuterClass.AckCommand.getDefaultInstance();
      }

      @java.lang.Override
      public com.arckal.soul.protos.AckCommandOuterClass.AckCommand build() {
        com.arckal.soul.protos.AckCommandOuterClass.AckCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.arckal.soul.protos.AckCommandOuterClass.AckCommand buildPartial() {
        com.arckal.soul.protos.AckCommandOuterClass.AckCommand result = new com.arckal.soul.protos.AckCommandOuterClass.AckCommand(this);
        result.remain_ = remain_;
        result.readLastMsgId_ = readLastMsgId_;
        result.timestamp_ = timestamp_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.arckal.soul.protos.AckCommandOuterClass.AckCommand) {
          return mergeFrom((com.arckal.soul.protos.AckCommandOuterClass.AckCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.arckal.soul.protos.AckCommandOuterClass.AckCommand other) {
        if (other == com.arckal.soul.protos.AckCommandOuterClass.AckCommand.getDefaultInstance()) return this;
        if (other.getRemain() != false) {
          setRemain(other.getRemain());
        }
        if (!other.getReadLastMsgId().isEmpty()) {
          readLastMsgId_ = other.readLastMsgId_;
          onChanged();
        }
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.arckal.soul.protos.AckCommandOuterClass.AckCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.arckal.soul.protos.AckCommandOuterClass.AckCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean remain_ ;
      /**
       * <code>bool remain = 1;</code>
       */
      public boolean getRemain() {
        return remain_;
      }
      /**
       * <code>bool remain = 1;</code>
       */
      public Builder setRemain(boolean value) {
        
        remain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool remain = 1;</code>
       */
      public Builder clearRemain() {
        
        remain_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object readLastMsgId_ = "";
      /**
       * <code>string readLastMsgId = 2;</code>
       */
      public java.lang.String getReadLastMsgId() {
        java.lang.Object ref = readLastMsgId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          readLastMsgId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string readLastMsgId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getReadLastMsgIdBytes() {
        java.lang.Object ref = readLastMsgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          readLastMsgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string readLastMsgId = 2;</code>
       */
      public Builder setReadLastMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        readLastMsgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string readLastMsgId = 2;</code>
       */
      public Builder clearReadLastMsgId() {
        
        readLastMsgId_ = getDefaultInstance().getReadLastMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>string readLastMsgId = 2;</code>
       */
      public Builder setReadLastMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        readLastMsgId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <code>string timestamp = 3;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string timestamp = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string timestamp = 3;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 3;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timestamp_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.com.arckal.soul.AckCommand.Type type = 4;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.com.arckal.soul.AckCommand.Type type = 4;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.arckal.soul.AckCommand.Type type = 4;</code>
       */
      public com.arckal.soul.protos.AckCommandOuterClass.AckCommand.Type getType() {
        @SuppressWarnings("deprecation")
        com.arckal.soul.protos.AckCommandOuterClass.AckCommand.Type result = com.arckal.soul.protos.AckCommandOuterClass.AckCommand.Type.valueOf(type_);
        return result == null ? com.arckal.soul.protos.AckCommandOuterClass.AckCommand.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.arckal.soul.AckCommand.Type type = 4;</code>
       */
      public Builder setType(com.arckal.soul.protos.AckCommandOuterClass.AckCommand.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.arckal.soul.AckCommand.Type type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.arckal.soul.AckCommand)
    }

    // @@protoc_insertion_point(class_scope:com.arckal.soul.AckCommand)
    private static final com.arckal.soul.protos.AckCommandOuterClass.AckCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.arckal.soul.protos.AckCommandOuterClass.AckCommand();
    }

    public static com.arckal.soul.protos.AckCommandOuterClass.AckCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AckCommand>
        PARSER = new com.google.protobuf.AbstractParser<AckCommand>() {
      @java.lang.Override
      public AckCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AckCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AckCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AckCommand> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.arckal.soul.protos.AckCommandOuterClass.AckCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_arckal_soul_AckCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_arckal_soul_AckCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020AckCommand.proto\022\017com.arckal.soul\"\254\001\n\n" +
      "AckCommand\022\016\n\006remain\030\001 \001(\010\022\025\n\rreadLastMs" +
      "gId\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\t\022.\n\004type\030\004 \001" +
      "(\0162 .com.arckal.soul.AckCommand.Type\"4\n\004" +
      "Type\022\007\n\003MSG\020\000\022\010\n\004SYNC\020\001\022\031\n\014UNRECOGNIZED\020" +
      "\377\377\377\377\377\377\377\377\377\001B\030\n\026com.arckal.soul.protosb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_arckal_soul_AckCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_arckal_soul_AckCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_arckal_soul_AckCommand_descriptor,
        new java.lang.String[] { "Remain", "ReadLastMsgId", "Timestamp", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
