// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgFin.proto

package com.arckal.soul.protos;

public final class MsgFinOuterClass {
  private MsgFinOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgFinOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.arckal.soul.MsgFin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string readLastMsgId = 1;</code>
     */
    java.lang.String getReadLastMsgId();
    /**
     * <code>string readLastMsgId = 1;</code>
     */
    com.google.protobuf.ByteString
        getReadLastMsgIdBytes();

    /**
     * <code>string timestamp = 2;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <code>string timestamp = 2;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <code>.com.arckal.soul.MsgFin.Status status = 3;</code>
     */
    int getStatusValue();
    /**
     * <code>.com.arckal.soul.MsgFin.Status status = 3;</code>
     */
    com.arckal.soul.protos.MsgFinOuterClass.MsgFin.Status getStatus();
  }
  /**
   * Protobuf type {@code com.arckal.soul.MsgFin}
   */
  public  static final class MsgFin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.arckal.soul.MsgFin)
      MsgFinOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgFin.newBuilder() to construct.
    private MsgFin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgFin() {
      readLastMsgId_ = "";
      timestamp_ = "";
      status_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgFin();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgFin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              readLastMsgId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              timestamp_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.arckal.soul.protos.MsgFinOuterClass.internal_static_com_arckal_soul_MsgFin_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.arckal.soul.protos.MsgFinOuterClass.internal_static_com_arckal_soul_MsgFin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.arckal.soul.protos.MsgFinOuterClass.MsgFin.class, com.arckal.soul.protos.MsgFinOuterClass.MsgFin.Builder.class);
    }

    /**
     * Protobuf enum {@code com.arckal.soul.MsgFin.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TODO = 0;</code>
       */
      TODO(0),
      /**
       * <code>DOING = 1;</code>
       */
      DOING(1),
      /**
       * <code>DONE = 2;</code>
       */
      DONE(2),
      /**
       * <code>UNRECOGNIZED = -1;</code>
       */
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>TODO = 0;</code>
       */
      public static final int TODO_VALUE = 0;
      /**
       * <code>DOING = 1;</code>
       */
      public static final int DOING_VALUE = 1;
      /**
       * <code>DONE = 2;</code>
       */
      public static final int DONE_VALUE = 2;
      /**
       * <code>UNRECOGNIZED = -1;</code>
       */
      public static final int UNRECOGNIZED_VALUE = -1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      public static Status forNumber(int value) {
        switch (value) {
          case 0: return TODO;
          case 1: return DOING;
          case 2: return DONE;
          case -1: return UNRECOGNIZED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.arckal.soul.protos.MsgFinOuterClass.MsgFin.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.arckal.soul.MsgFin.Status)
    }

    public static final int READLASTMSGID_FIELD_NUMBER = 1;
    private volatile java.lang.Object readLastMsgId_;
    /**
     * <code>string readLastMsgId = 1;</code>
     */
    public java.lang.String getReadLastMsgId() {
      java.lang.Object ref = readLastMsgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        readLastMsgId_ = s;
        return s;
      }
    }
    /**
     * <code>string readLastMsgId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReadLastMsgIdBytes() {
      java.lang.Object ref = readLastMsgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        readLastMsgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private volatile java.lang.Object timestamp_;
    /**
     * <code>string timestamp = 2;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <code>string timestamp = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <code>.com.arckal.soul.MsgFin.Status status = 3;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.arckal.soul.MsgFin.Status status = 3;</code>
     */
    public com.arckal.soul.protos.MsgFinOuterClass.MsgFin.Status getStatus() {
      @SuppressWarnings("deprecation")
      com.arckal.soul.protos.MsgFinOuterClass.MsgFin.Status result = com.arckal.soul.protos.MsgFinOuterClass.MsgFin.Status.valueOf(status_);
      return result == null ? com.arckal.soul.protos.MsgFinOuterClass.MsgFin.Status.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getReadLastMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, readLastMsgId_);
      }
      if (!getTimestampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, timestamp_);
      }
      if (status_ != com.arckal.soul.protos.MsgFinOuterClass.MsgFin.Status.TODO.getNumber()) {
        output.writeEnum(3, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getReadLastMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, readLastMsgId_);
      }
      if (!getTimestampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, timestamp_);
      }
      if (status_ != com.arckal.soul.protos.MsgFinOuterClass.MsgFin.Status.TODO.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.arckal.soul.protos.MsgFinOuterClass.MsgFin)) {
        return super.equals(obj);
      }
      com.arckal.soul.protos.MsgFinOuterClass.MsgFin other = (com.arckal.soul.protos.MsgFinOuterClass.MsgFin) obj;

      if (!getReadLastMsgId()
          .equals(other.getReadLastMsgId())) return false;
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
      if (status_ != other.status_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + READLASTMSGID_FIELD_NUMBER;
      hash = (53 * hash) + getReadLastMsgId().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.arckal.soul.protos.MsgFinOuterClass.MsgFin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.arckal.soul.protos.MsgFinOuterClass.MsgFin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.arckal.soul.protos.MsgFinOuterClass.MsgFin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.arckal.soul.protos.MsgFinOuterClass.MsgFin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.arckal.soul.protos.MsgFinOuterClass.MsgFin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.arckal.soul.protos.MsgFinOuterClass.MsgFin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.arckal.soul.protos.MsgFinOuterClass.MsgFin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.arckal.soul.protos.MsgFinOuterClass.MsgFin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.arckal.soul.protos.MsgFinOuterClass.MsgFin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.arckal.soul.protos.MsgFinOuterClass.MsgFin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.arckal.soul.protos.MsgFinOuterClass.MsgFin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.arckal.soul.protos.MsgFinOuterClass.MsgFin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.arckal.soul.protos.MsgFinOuterClass.MsgFin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.arckal.soul.MsgFin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.arckal.soul.MsgFin)
        com.arckal.soul.protos.MsgFinOuterClass.MsgFinOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.arckal.soul.protos.MsgFinOuterClass.internal_static_com_arckal_soul_MsgFin_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.arckal.soul.protos.MsgFinOuterClass.internal_static_com_arckal_soul_MsgFin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.arckal.soul.protos.MsgFinOuterClass.MsgFin.class, com.arckal.soul.protos.MsgFinOuterClass.MsgFin.Builder.class);
      }

      // Construct using com.arckal.soul.protos.MsgFinOuterClass.MsgFin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        readLastMsgId_ = "";

        timestamp_ = "";

        status_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.arckal.soul.protos.MsgFinOuterClass.internal_static_com_arckal_soul_MsgFin_descriptor;
      }

      @java.lang.Override
      public com.arckal.soul.protos.MsgFinOuterClass.MsgFin getDefaultInstanceForType() {
        return com.arckal.soul.protos.MsgFinOuterClass.MsgFin.getDefaultInstance();
      }

      @java.lang.Override
      public com.arckal.soul.protos.MsgFinOuterClass.MsgFin build() {
        com.arckal.soul.protos.MsgFinOuterClass.MsgFin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.arckal.soul.protos.MsgFinOuterClass.MsgFin buildPartial() {
        com.arckal.soul.protos.MsgFinOuterClass.MsgFin result = new com.arckal.soul.protos.MsgFinOuterClass.MsgFin(this);
        result.readLastMsgId_ = readLastMsgId_;
        result.timestamp_ = timestamp_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.arckal.soul.protos.MsgFinOuterClass.MsgFin) {
          return mergeFrom((com.arckal.soul.protos.MsgFinOuterClass.MsgFin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.arckal.soul.protos.MsgFinOuterClass.MsgFin other) {
        if (other == com.arckal.soul.protos.MsgFinOuterClass.MsgFin.getDefaultInstance()) return this;
        if (!other.getReadLastMsgId().isEmpty()) {
          readLastMsgId_ = other.readLastMsgId_;
          onChanged();
        }
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.arckal.soul.protos.MsgFinOuterClass.MsgFin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.arckal.soul.protos.MsgFinOuterClass.MsgFin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object readLastMsgId_ = "";
      /**
       * <code>string readLastMsgId = 1;</code>
       */
      public java.lang.String getReadLastMsgId() {
        java.lang.Object ref = readLastMsgId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          readLastMsgId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string readLastMsgId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReadLastMsgIdBytes() {
        java.lang.Object ref = readLastMsgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          readLastMsgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string readLastMsgId = 1;</code>
       */
      public Builder setReadLastMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        readLastMsgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string readLastMsgId = 1;</code>
       */
      public Builder clearReadLastMsgId() {
        
        readLastMsgId_ = getDefaultInstance().getReadLastMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>string readLastMsgId = 1;</code>
       */
      public Builder setReadLastMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        readLastMsgId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <code>string timestamp = 2;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string timestamp = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string timestamp = 2;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 2;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timestamp_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.com.arckal.soul.MsgFin.Status status = 3;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.com.arckal.soul.MsgFin.Status status = 3;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.arckal.soul.MsgFin.Status status = 3;</code>
       */
      public com.arckal.soul.protos.MsgFinOuterClass.MsgFin.Status getStatus() {
        @SuppressWarnings("deprecation")
        com.arckal.soul.protos.MsgFinOuterClass.MsgFin.Status result = com.arckal.soul.protos.MsgFinOuterClass.MsgFin.Status.valueOf(status_);
        return result == null ? com.arckal.soul.protos.MsgFinOuterClass.MsgFin.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.arckal.soul.MsgFin.Status status = 3;</code>
       */
      public Builder setStatus(com.arckal.soul.protos.MsgFinOuterClass.MsgFin.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.arckal.soul.MsgFin.Status status = 3;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.arckal.soul.MsgFin)
    }

    // @@protoc_insertion_point(class_scope:com.arckal.soul.MsgFin)
    private static final com.arckal.soul.protos.MsgFinOuterClass.MsgFin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.arckal.soul.protos.MsgFinOuterClass.MsgFin();
    }

    public static com.arckal.soul.protos.MsgFinOuterClass.MsgFin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgFin>
        PARSER = new com.google.protobuf.AbstractParser<MsgFin>() {
      @java.lang.Override
      public MsgFin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgFin(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgFin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgFin> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.arckal.soul.protos.MsgFinOuterClass.MsgFin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_arckal_soul_MsgFin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_arckal_soul_MsgFin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014MsgFin.proto\022\017com.arckal.soul\"\246\001\n\006MsgF" +
      "in\022\025\n\rreadLastMsgId\030\001 \001(\t\022\021\n\ttimestamp\030\002" +
      " \001(\t\022.\n\006status\030\003 \001(\0162\036.com.arckal.soul.M" +
      "sgFin.Status\"B\n\006Status\022\010\n\004TODO\020\000\022\t\n\005DOIN" +
      "G\020\001\022\010\n\004DONE\020\002\022\031\n\014UNRECOGNIZED\020\377\377\377\377\377\377\377\377\377\001" +
      "B\030\n\026com.arckal.soul.protosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_arckal_soul_MsgFin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_arckal_soul_MsgFin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_arckal_soul_MsgFin_descriptor,
        new java.lang.String[] { "ReadLastMsgId", "Timestamp", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
