// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PicMessage.proto

package com.arckal.soul.protos;

public final class PicMessageOuterClass {
  private PicMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PicMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.arckal.soul.PicMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float imageW = 1;</code>
     */
    float getImageW();

    /**
     * <code>float imageH = 2;</code>
     */
    float getImageH();

    /**
     * <code>string imageUrl = 3;</code>
     */
    java.lang.String getImageUrl();
    /**
     * <code>string imageUrl = 3;</code>
     */
    com.google.protobuf.ByteString
        getImageUrlBytes();
  }
  /**
   * Protobuf type {@code com.arckal.soul.PicMessage}
   */
  public  static final class PicMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.arckal.soul.PicMessage)
      PicMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PicMessage.newBuilder() to construct.
    private PicMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PicMessage() {
      imageUrl_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PicMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PicMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              imageW_ = input.readFloat();
              break;
            }
            case 21: {

              imageH_ = input.readFloat();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              imageUrl_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.arckal.soul.protos.PicMessageOuterClass.internal_static_com_arckal_soul_PicMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.arckal.soul.protos.PicMessageOuterClass.internal_static_com_arckal_soul_PicMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.arckal.soul.protos.PicMessageOuterClass.PicMessage.class, com.arckal.soul.protos.PicMessageOuterClass.PicMessage.Builder.class);
    }

    public static final int IMAGEW_FIELD_NUMBER = 1;
    private float imageW_;
    /**
     * <code>float imageW = 1;</code>
     */
    public float getImageW() {
      return imageW_;
    }

    public static final int IMAGEH_FIELD_NUMBER = 2;
    private float imageH_;
    /**
     * <code>float imageH = 2;</code>
     */
    public float getImageH() {
      return imageH_;
    }

    public static final int IMAGEURL_FIELD_NUMBER = 3;
    private volatile java.lang.Object imageUrl_;
    /**
     * <code>string imageUrl = 3;</code>
     */
    public java.lang.String getImageUrl() {
      java.lang.Object ref = imageUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string imageUrl = 3;</code>
     */
    public com.google.protobuf.ByteString
        getImageUrlBytes() {
      java.lang.Object ref = imageUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (imageW_ != 0F) {
        output.writeFloat(1, imageW_);
      }
      if (imageH_ != 0F) {
        output.writeFloat(2, imageH_);
      }
      if (!getImageUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, imageUrl_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (imageW_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, imageW_);
      }
      if (imageH_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, imageH_);
      }
      if (!getImageUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, imageUrl_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.arckal.soul.protos.PicMessageOuterClass.PicMessage)) {
        return super.equals(obj);
      }
      com.arckal.soul.protos.PicMessageOuterClass.PicMessage other = (com.arckal.soul.protos.PicMessageOuterClass.PicMessage) obj;

      if (java.lang.Float.floatToIntBits(getImageW())
          != java.lang.Float.floatToIntBits(
              other.getImageW())) return false;
      if (java.lang.Float.floatToIntBits(getImageH())
          != java.lang.Float.floatToIntBits(
              other.getImageH())) return false;
      if (!getImageUrl()
          .equals(other.getImageUrl())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IMAGEW_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getImageW());
      hash = (37 * hash) + IMAGEH_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getImageH());
      hash = (37 * hash) + IMAGEURL_FIELD_NUMBER;
      hash = (53 * hash) + getImageUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.arckal.soul.protos.PicMessageOuterClass.PicMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.arckal.soul.protos.PicMessageOuterClass.PicMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.arckal.soul.protos.PicMessageOuterClass.PicMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.arckal.soul.protos.PicMessageOuterClass.PicMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.arckal.soul.protos.PicMessageOuterClass.PicMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.arckal.soul.protos.PicMessageOuterClass.PicMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.arckal.soul.protos.PicMessageOuterClass.PicMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.arckal.soul.protos.PicMessageOuterClass.PicMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.arckal.soul.protos.PicMessageOuterClass.PicMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.arckal.soul.protos.PicMessageOuterClass.PicMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.arckal.soul.protos.PicMessageOuterClass.PicMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.arckal.soul.protos.PicMessageOuterClass.PicMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.arckal.soul.protos.PicMessageOuterClass.PicMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.arckal.soul.PicMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.arckal.soul.PicMessage)
        com.arckal.soul.protos.PicMessageOuterClass.PicMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.arckal.soul.protos.PicMessageOuterClass.internal_static_com_arckal_soul_PicMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.arckal.soul.protos.PicMessageOuterClass.internal_static_com_arckal_soul_PicMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.arckal.soul.protos.PicMessageOuterClass.PicMessage.class, com.arckal.soul.protos.PicMessageOuterClass.PicMessage.Builder.class);
      }

      // Construct using com.arckal.soul.protos.PicMessageOuterClass.PicMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        imageW_ = 0F;

        imageH_ = 0F;

        imageUrl_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.arckal.soul.protos.PicMessageOuterClass.internal_static_com_arckal_soul_PicMessage_descriptor;
      }

      @java.lang.Override
      public com.arckal.soul.protos.PicMessageOuterClass.PicMessage getDefaultInstanceForType() {
        return com.arckal.soul.protos.PicMessageOuterClass.PicMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.arckal.soul.protos.PicMessageOuterClass.PicMessage build() {
        com.arckal.soul.protos.PicMessageOuterClass.PicMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.arckal.soul.protos.PicMessageOuterClass.PicMessage buildPartial() {
        com.arckal.soul.protos.PicMessageOuterClass.PicMessage result = new com.arckal.soul.protos.PicMessageOuterClass.PicMessage(this);
        result.imageW_ = imageW_;
        result.imageH_ = imageH_;
        result.imageUrl_ = imageUrl_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.arckal.soul.protos.PicMessageOuterClass.PicMessage) {
          return mergeFrom((com.arckal.soul.protos.PicMessageOuterClass.PicMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.arckal.soul.protos.PicMessageOuterClass.PicMessage other) {
        if (other == com.arckal.soul.protos.PicMessageOuterClass.PicMessage.getDefaultInstance()) return this;
        if (other.getImageW() != 0F) {
          setImageW(other.getImageW());
        }
        if (other.getImageH() != 0F) {
          setImageH(other.getImageH());
        }
        if (!other.getImageUrl().isEmpty()) {
          imageUrl_ = other.imageUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.arckal.soul.protos.PicMessageOuterClass.PicMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.arckal.soul.protos.PicMessageOuterClass.PicMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float imageW_ ;
      /**
       * <code>float imageW = 1;</code>
       */
      public float getImageW() {
        return imageW_;
      }
      /**
       * <code>float imageW = 1;</code>
       */
      public Builder setImageW(float value) {
        
        imageW_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float imageW = 1;</code>
       */
      public Builder clearImageW() {
        
        imageW_ = 0F;
        onChanged();
        return this;
      }

      private float imageH_ ;
      /**
       * <code>float imageH = 2;</code>
       */
      public float getImageH() {
        return imageH_;
      }
      /**
       * <code>float imageH = 2;</code>
       */
      public Builder setImageH(float value) {
        
        imageH_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float imageH = 2;</code>
       */
      public Builder clearImageH() {
        
        imageH_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object imageUrl_ = "";
      /**
       * <code>string imageUrl = 3;</code>
       */
      public java.lang.String getImageUrl() {
        java.lang.Object ref = imageUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imageUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string imageUrl = 3;</code>
       */
      public com.google.protobuf.ByteString
          getImageUrlBytes() {
        java.lang.Object ref = imageUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string imageUrl = 3;</code>
       */
      public Builder setImageUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string imageUrl = 3;</code>
       */
      public Builder clearImageUrl() {
        
        imageUrl_ = getDefaultInstance().getImageUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string imageUrl = 3;</code>
       */
      public Builder setImageUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageUrl_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.arckal.soul.PicMessage)
    }

    // @@protoc_insertion_point(class_scope:com.arckal.soul.PicMessage)
    private static final com.arckal.soul.protos.PicMessageOuterClass.PicMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.arckal.soul.protos.PicMessageOuterClass.PicMessage();
    }

    public static com.arckal.soul.protos.PicMessageOuterClass.PicMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PicMessage>
        PARSER = new com.google.protobuf.AbstractParser<PicMessage>() {
      @java.lang.Override
      public PicMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PicMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PicMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PicMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.arckal.soul.protos.PicMessageOuterClass.PicMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_arckal_soul_PicMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_arckal_soul_PicMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020PicMessage.proto\022\017com.arckal.soul\">\n\nP" +
      "icMessage\022\016\n\006imageW\030\001 \001(\002\022\016\n\006imageH\030\002 \001(" +
      "\002\022\020\n\010imageUrl\030\003 \001(\tB\030\n\026com.arckal.soul.p" +
      "rotosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_arckal_soul_PicMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_arckal_soul_PicMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_arckal_soul_PicMessage_descriptor,
        new java.lang.String[] { "ImageW", "ImageH", "ImageUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
